name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'fix/integration-test'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  test:
    runs-on: [F74136885]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-mock pytest-cov

      # - name: Run unit tests
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: |
      #     cd backend
      #     pytest tests/unit --cov=src --cov-report=xml --disable-warnings
      - name: Create .env file
        run: |
          echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
      - name: Run integration tests (with mock DB)
        run: |
          cd backend
          pytest tests/integration --cov=src --cov-report=xml --disable-warnings

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.12"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install flake8

  #     - name: Run flake8
  #       run: |
  #         flake8 backend --count --max-line-length=150 --statistics
